services:
  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: sintra_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  web_test:
    build: .
    env_file: .env
    environment:
      DB_HOST: db_test
      DB_PORT: "5432"
      DJANGO_WSGI_MODULE: core.wsgi
      DJANGO_SETTINGS_MODULE: core.settings
    depends_on:
      - db_test
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume_test:/app/staticfiles
      - media_volume_test:/app/media

  nginx_test:
    image: nginx:alpine
    depends_on:
      - web_test
    ports:
      - "8080:80"
    volumes:
      - ./nginx/sintra.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume_test:/var/www/static
      - media_volume_test:/var/www/media

volumes:
  pgdata_test:
    external: true
    name: sintra_test_pgdata_test           # <<< el que tiene tus datos
  static_volume_test:
    external: true
    name: sintra_test_static_volume_test    # <<< el que tiene tus estÃ¡ticos
  media_volume_test:
    external: true
    name: sintra_test_media_volume_test     # <<< el que tiene tus medias
